{{- if .Values.frontend.ingress.enabled -}}
{{- $svcName := printf "%s-service" .Values.frontend.name -}}
{{- $svcPort := .Values.frontend.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.frontend.name }}-ingress
  labels:
    {{- include "polkassembly.frontend.matchLabels" . | nindent 4 }}
  {{- with .Values.frontend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.frontend.ingress.tls }}
  tls:
    - hosts:
      {{- range .Values.frontend.ingress.tls.hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{  .Values.frontend.ingress.tls.secretName }}
{{- end }}
  rules:
  {{- range .Values.frontend.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $svcName }}
                port:
                  number: {{ $svcPort }}
  {{- end }}
{{- end }}
