---
kind: Namespace
apiVersion: v1
metadata:
  name: polkassembly
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: gitlab
  namespace: polkassembly
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab
  namespace: polkassembly
subjects:
- kind: ServiceAccount
  name: gitlab
  namespace: polkassembly
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: kusama-polkassembly-io
  namespace: polkassembly
spec:
  domains:
    - kusama.polkassembly.io
